version: '3.8'

services:
  api:
    build: .
    container_name: color-suggester-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - ENVIRONMENT=production
    restart: unless-stopped